updated bpmn module to decouple xml from builder
byu-vv-lab/bpmn_cwp_verify pull request #87
Opened 2024-12-21 02:54 UTC by tklaback

2025-01-13 23:53 UTC, ericmercer commented on src/bpmncwpverify/core/bpmn.py
> +        from bpmncwpverify.builder.process_builder import ProcessBuilder
Move the imports to the top of the file.  I think that is the preferred style so that all dependencies are in one place.

2025-01-13 23:56 UTC, ericmercer requested changes
Minor changes as noted in the comments.

2025-01-14 19:11 UTC, ericmercer commented on src/bpmncwpverify/core/bpmn.py
> +        from bpmncwpverify.builder.process_builder import ProcessBuilder
Where is the circular dependency coming from?  Is it unavoidable or a result of organization that needs to be fixed? If it's unavoidable, then let's go with the fix here. If it's an organization issue, then led's reorganize as appropriate.

2025-01-14 19:22 UTC, tklaback commented on src/bpmncwpverify/core/bpmn.py
> +        from bpmncwpverify.builder.process_builder import ProcessBuilder
@ericmercer great question, I'll look into whether we can resolve this at an organization level.

2025-01-14 19:41 UTC, tklaback commented on src/bpmncwpverify/core/bpmn.py
> +        from bpmncwpverify.builder.process_builder import ProcessBuilder
Okay @ericmercer , it looks it is inevitable. The ProcessBuilder needs the types from the bpmn module and the bpmn module needs the ProcessBuilder in order to build a process from `Process.from_xml`.

2025-01-15 18:04 UTC, ericmercer approved these changes
Will you please work on a proposal that breaks the circular dependency? I suggest that we need move types around for the builder so that it only depends on what belongs in a process and not the actual workflow captured in the BPMN. I'll open an issue so that we don't lose track of it.

2025-01-15 18:08 UTC, merged